### ISSUE TITLE
Battery pops out and hood cannot be opened in 2.7-dev.4

### ISSUE THREAD

**Issue by Kattus** [Athlon007/MOP#23]
**Describe the bug**
Since updating to 2.7-dev.4 I can no longer open the stock hood, it just pops up a few centimetres and clicking it only makes it "bounce" a bit. Battery also always pops out and needs to be re-attached every load.

**To Reproduce**
1. Load save where car has hood and battery installed
2. Hear a crash outside when mod loads, battery pops out
3. Hood will "pop" with hood lock but cannot be swung open.

**Expected behavior**
Battery to stay in place, hood to be openable

**Game Version:**
Experimental

**Mod Report:**
https://gist.github.com/Kattus/0bd3c170de753fef89da8771e42b5782

**Additional context**
This did not happen in the previous dev release, but it seems the binary has been removed from releases so I cannot test. Also doesnt happen when disabling the mod.
Savefile for testing: [msc.zip](https://github.com/Athlon007/MOP/files/4539194/msc.zip)

**Comment by Athlon007** [comment]
I'm aware of that issue, I'll fix it asap.

**Comment by Athlon007** [comment]
Fixed in 2.7. If half of the people reported bugs like you, there would be 90% less bugs in MOP...

**Comment by Kattus** [comment]
Sadly the battery popping out is still happening with 2.7.. :(
![](https://steamuserimages-a.akamaihd.net/ugc/1013816953982452424/3BDE127971D3FAB9E1EE74A7CAE985A192F20771/)

**Comment by Athlon007** [comment]
I just found the issue with batteries. The same may also apply for the oil filters and spark plugs. Update soon.

**Comment by Kattus** [comment]
Weird, my sparkplugs and oil filter is staying in place, worth mentioning I am not using the stock oil filter.

**Comment by Athlon007** [comment]
Looks like the battery and the rest of the items I mentioned are two separate things.

The battery issue is similar one to the popping off hood.

**Comment by Kattus** [comment]
All seems to be fine in 2.7.1, thanks! <3
